server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source
    url: jdbc:mysql://board.cysyk2b0tqz4.ap-northeast-2.rds.amazonaws.com:3306/Board?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    # DB username
    username: jhkang1995
    # DB password
    password: kang13131204
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

